server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: homework-application
  
  datasource:
    url: jdbc:mysql://localhost:3306/homework_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}
  
  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:ashfak25321@gmail.com}
    password: ${EMAIL_PASSWORD:thfn qrst ozqf dvzlthfn qrst ozqf dvzl}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
    default-encoding: UTF-8
  
  # security:
  #   user:
  #     name: admin
  #     password: admin123

jwt:
  secret: 12345678901234567890123456789012
  expiration: 86400000  # 24 hours in milliseconds

# Email Templates Configuration
email:
  from: ${EMAIL_FROM:ashfak25321@gmail.com}
  templates:
    new-homework: "New Homework Assignment: {title}"
    due-soon: "Homework Due Soon: {title}"
    overdue: "Homework Overdue: {title}"
    graded: "Homework Graded: {title}"
    submission: "Homework Submission Received: {title}"

logging:
  level:
    root: INFO
    com.homework: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 