server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: homework-application
  
  datasource:
    url: jdbc:mysql://localhost:3306/homework_db
    username: root
    password: Ashmhmd25321
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  security:
    user:
      name: admin
      password: admin123

jwt:
  secret: your-256-bit-secret
  expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    root: INFO
    com.homework: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 